service: themeflight
configValidationMode: error

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-1
  role: arn:aws:iam::530158470050:role/themeflight-dev-us-east-1-lambdaRole
  environment:
    NODE_ENV: production
    REGION: us-east-1
    SECRET_NAME: 'arn:aws:secretsmanager:us-east-1:530158470050:secret:dev-themeflight-3QPq2Q'
    DB_HOST: 'devthemeflight.c87z4vavipyc.us-east-1.rds.amazonaws.com'
    DB_PORT: 5432
    DB_NAME: 'themeflight'
    DB_USER: 'dbuser'
    DB_PASSWORD: 'Password2021!'
    DB_MIN_POOL: 2
    DB_MAX_POOL: 10

functions:
  api:
    handler: lambda.handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}
    package:
      include:
        - dist/**
        - package.json
        - lambda.js
        - static/**
        - public/**
      exclude:
        - '*'
        - node_modules/**
        - .github/**
        - .vscode/**
        - __test__/**
        - docs/**
        - db/**
  # theme-worker:
  #   handler: dist/lambda/theme-lambda.handler
  #   timeout: 600
  #   events:
  #     - schedule:
  #       rate: rate(10 minutes)
  #       enabled: true
  # schedule-worker:
  #   handler: dist/lambda/schedule-lambda.hanlder
  #   timeout: 600
  #   events:
  #     - schedule:
  #       rate: rate(1 minutes)
  #       enabled: true
