service: themeflight
configValidationMode: error

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-1
  role: arn:aws:iam::530158470050:role/themeflight-dev-us-east-1-lambdaRole
  environment:
    NODE_ENV: production
    REGION: us-east-1
    SECRET_NAME: 'arn:aws:secretsmanager:us-east-1:530158470050:secret:dev-themeflight-3QPq2Q'

functions:
  api:
    handler: lambda.handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}
    package:
      include:
        - dist/**
        - package.json
        - lambda.js
      exclude:
        - '*'
        - node_modules/**
        - .github/**
        - .vscode/**
        - __test__/**
        - docs/**
        - db/**
  theme-worker:
    handler: dist/lambda/theme-lambda.handler
    timeout: 600
    events:
      - schedule:
        rate: rate(10 minutes)
        enabled: true
  schedule-worker:
    handler: dist/lambda/schedule-lambda.hanlder
    timeout: 600
    events:
      - schedule:
        rate: rate(1 minutes)
        enabled: true
