service: themeflight
configValidationMode: error

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-1
  environment:
    NODE_ENV: production
    REGION: us-east-1
    SECRET_NAME: 'arn:aws:secretsmanager:us-east-1:530158470050:secret:dev-themeflight-3QPq2Q'

functions:
  app:
    handler: lambda.handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}
