export const ALLOWED_WEBHOOKS = {
  THEME_CREATE: 'themes/create',
  THEME_PUBLISH: 'themes/publish',
  THEME_UPDATE: 'themes/update'
};

export const VAlIDATION_RESPONSE_CODE = {
  NOT_FOUND_SHOP: 'NOT_FOUND_SHOP',
  NOT_FOUND_THEMES: 'NOT_FOUND_THEMES',
  NOT_FOUND_WEBHOOKS: 'NOT_FOUND_WEBHOOKS',
  ACCESS_TOKEN_REQUIRED: 'ACCESS_TOKEN_REQUIRED',
  ACCESS_TOKEN_NOT_MATCH: 'ACCESS_TOKEN_NOT_MATCH'
};
